### ISSUE TITLE
parallelize requests across different rotating accounts

### ISSUE THREAD

**Issue by xizhao** [zachlatta/2-dollar-dinosaurs#13]
so i added rate limiting and the pm api seems to work fine as long as we rate limit requests for 5.001/sec in between

this results in unacceptable performance for fetching menus as that bundles often 3+ requests together for 10+ sec res times

I propose we rotate accounts and assign 5 sec/acc as the rate limit individually

this also makes things harder to detect kind of

can we make this repo private?

**Comment by xizhao** [comment]
7ea9590429ad7944aeac4e1b37c9d8524b160ee5

**Comment by zachlatta** [comment]
Perhaps we could make a copy of this repo and make that private.
